name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_jupyter-chat:
    runs-on: ubuntu-latest
    name: Build jupyter_chat

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: python -m pip install -U "jupyterlab>=4.0.0,<5"

    - name: Lint the packages
      run: |
        set -eux
        jlpm
        jlpm run lint:check

    - name: Build the core package
      run: jlpm build:core

    - name: Test the packages
      run: |
        set -eux
        jlpm run test

  build_extensions:
    runs-on: ubuntu-latest
    needs: build_jupyter-chat
    strategy:
      matrix:
        extension: [collaborative, websocket]
    name: Build ${{ matrix.extension }} chat extension
    env:
      PACKAGE: fromJSON('["jupyterlab_ws_chat", "jupyterlab_${{ matrix.extension }}_chat"]')[matrix.extension == 'websocket']
      DIRECTORY: fromJSON('["packages/jupyterlab-ws-chat", "packages/jupyterlab-${{ matrix.extension }}-chat"]')[matrix.extension == 'websocket']

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: python -m pip install -U "jupyterlab>=4.0.0,<5"

    - name: Build package
      run:  |
        jlpm install
        jlpm build:${{ matrix.extension }}

    - name: Package ${{ env.PACKAGE }}
      working-directory: ${{ env.DIRECTORY }}
      run: |
        set -eux
        pip install build
        python -m build
        pip uninstall -y "${{ env.PACKAGE }}" jupyterlab

    - name: Upload ${{ env.PACKAGE }} package
      uses: actions/upload-artifact@v3
      with:
        name: package-artifacts
        path: ${{ env.DIRECTORY }}/dist/${{ env.PACKAGE }}*
        if-no-files-found: error

  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: jupyterlab/maintainer-tools/.github/actions/check-links@v1
